language: r
cache:
  packages: true
  directories:
  - docs
pandoc_version: 1.19.2.1
sudo: true
r: 
  - bioc-devel
  - bioc-release
addons:
  apt:
    packages:
    - libxml2-dev
r_github_packages:
  - jimhester/covr
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ca-certificates
after_success:
  - Rscript -e 'covr::codecov()'
